"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['YoutubeM4aDownloader.py']
DATA_FILES = ['YoutubeM4aDownloader.xib']
OPTIONS = {
	'iconfile':'icon.icns',
	'plist': {'CFBundleShortVersionString':'0.1.0','CFBundleGetInfoString':'Ben','NSHumanReadableCopyright':'thenet',}
}

setup(
    app=APP,
    name='YoutubeM4aDownloader',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
